# Import R packages needed for the UI
library(shiny)
library(shinycssloaders)
library(DT)

# Begin UI for the R + reticulate example app
ui <- fluidPage(
  
  titlePanel('Matched Data Evaluation and Variable Importance'),
  
  sidebarLayout(
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    sidebarPanel(
      fileInput('file1', 'Choose CSV File',
                accept=c('text/csv', 
                         'text/comma-separated-values,text/plain', 
                         '.csv')),
      # Input: Select number of rows to display ----
      radioButtons("disp", "Display",
                   choices = c(Head = "head",
                               All = "all"),
                   selected = "head"),
      br(),
      
      h5("Select Dependent and Independent Variables"),
      tags$hr(),
      uiOutput("outcomeVar"),
      tags$hr(),
      uiOutput("independents"),
      tags$hr(),
      actionButton("random", "Estimate mixed effects model"),
      tags$hr(),
    
    ),
    
    # ---------------- Sidebar panel with changeable inputs ----------------- #
    mainPanel(
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = 'tabs',
                  tabPanel('Using R and Python functions', 
                           br(),
                           h3('Here is imported .csv file'),
                           tableOutput("contents")),
                           #h3('Outputs generated with pure R'),
                           #br(),
                           #withSpinner(plotOutput('plot')),
                           #br(),
                           #h3('Outputs generated by Python functions via reticulate'),
                           #verbatimTextOutput('message'),
                           #br(),
                           #'Use the numpy Python package to add two numbers',
                           #verbatimTextOutput('xy')),
                           
                  tabPanel('Architecture Info', 
                           h3('Current architecture info'),
                           '(These values will change when app is run locally vs on Shinyapps.io)',
                           hr(),
                           withSpinner(DT::dataTableOutput('sysinfo')),
                           br(),
                           verbatimTextOutput('which_python'),
                           verbatimTextOutput('python_version'),
                           verbatimTextOutput('ret_env_var'),
                           verbatimTextOutput('venv_root')),
                  
                  tabPanel('Summary of linear model',
                           h4("Here is a summary of linear model"),
                           verbatimTextOutput("linearModel")
                  ),
                  
      )
    )
  )
)
